import React from 'react';
import {
    RefreshCcw,
    Shield,
    Pill,
    Database,
    AlertTriangle,
    Cross,
    Stethoscope,
    User,
    Mail,
    Lock,
    Eye,
    Bell,
    LogOut,
    ShieldPlus,
    LayoutDashboard,
    ScanLine,
    ClipboardCheck,
    Settings,
    BellRing,
    FileText,
    Users,
    Search,
    CheckCircle2,
    Trash2,
    Info,
    Sun,
    Focus,
    ShieldCheck,
    CheckCircle,
    ChevronRight,
    Image as ImageIcon,
    Type,
    Network,
    PlusCircle,
    History,
    Receipt,
    Clock,
    BadgeCheck,
    AlertCircle,
    Copy,
    Flag,
    Check,
    Upload,
    ImagePlus,
    Camera,
    Moon
} from 'lucide-react';

const iconMap = {
    refresh: RefreshCcw,
    shield_moon: Shield,
    pill: Pill,
    database: Database,
    warning: AlertTriangle,
    local_pharmacy: Cross,
    medical_services: Stethoscope,
    person: User,
    mail: Mail,
    lock: Lock,
    visibility: Eye,
    notifications: Bell,
    logout: LogOut,
    health_and_safety: ShieldPlus,
    dashboard: LayoutDashboard,
    qr_code_scanner: ScanLine,
    fact_check: ClipboardCheck,
    settings: Settings,
    notifications_active: BellRing,
    prescriptions: FileText, // approximation
    group: Users,
    search: Search,
    task_alt: CheckCircle2,
    delete: Trash2,
    info: Info,
    light_mode: Sun,
    center_focus_strong: Focus,
    security: ShieldCheck,
    check_circle: CheckCircle,
    chevron_right: ChevronRight,
    image: ImageIcon,
    font_download: Type,
    description: FileText,
    hub: Network,
    add_circle: PlusCircle,
    history: History,
    receipt_long: Receipt,
    pending_actions: Clock,
    verified: BadgeCheck,
    notification_important: AlertCircle,
    content_copy: Copy,
    flag: Flag,
    check: Check,
    upload_file: Upload,
    add_photo_alternate: ImagePlus,
    photo_camera: Camera,
    dark_mode: Moon,
};

export default function Icon({ name, className, size = 24 }) {
    const LucideIcon = iconMap[name];

    if (!LucideIcon) {
        console.warn(`Icon "${name}" not found in Icon.jsx map.`);
        return <span className={`inline-block w-5 h-5 bg-danger/20 rounded ${className}`} title={name} />;
    }

    return <LucideIcon size={size} className={className} />;
}
